//
// Created by Jonas on 29-12-2017.
//

#ifndef GAMEGEOMETRY_GLOBALTESTDEFINITIONS_H
#define GAMEGEOMETRY_GLOBALTESTDEFINITIONS_H

#define EXPECT_VECTOR2_EQ(VEC1, X, Y) EXPECT_FLOAT_EQ(VEC1.x, X);EXPECT_FLOAT_EQ(VEC1.y, Y);
#define EXPECT_VECTOR3_EQ(VEC1, X, Y, Z) EXPECT_FLOAT_EQ(VEC1.x, X);EXPECT_FLOAT_EQ(VEC1.y, Y);EXPECT_FLOAT_EQ(VEC1.z, Z);

#endif //GAMEGEOMETRY_GLOBALTESTDEFINITIONS_H
