//
// Created by Jonas on 29-12-2017.
//

#ifndef GAMEGEOMETRY_GLOBALTESTDEFINITIONS_H
#define GAMEGEOMETRY_GLOBALTESTDEFINITIONS_H

#define EXPECT_VECTOR2_EQ(VEC1, X, Y) EXPECT_EQ(VEC1.x, X);EXPECT_EQ(VEC1.y, Y);
#define EXPECT_VECTOR3_EQ(VEC1, X, Y, Z) EXPECT_EQ(VEC1.x, X);EXPECT_EQ(VEC1.y, Y);EXPECT_EQ(VEC1.z, Z);

#define EXPECT_MATRIX3_EQ(MAT, ARRAY) for(int i = 0; i < 9; i++) {EXPECT_EQ(MAT[i], ARRAY[i]);}

#define EXPECT_AABB_EQ(AABB, LEFT, RIGHT, TOP, BOTTOM) EXPECT_EQ(AABB.left, LEFT);EXPECT_EQ(AABB.left, LEFT);EXPECT_EQ(AABB.top, TOP);EXPECT_EQ(AABB.bottom, BOTTOM);

#define EXPECT_ARRAY_EQUAL(ARRAY1, ARRAY2, COUNT) for(int i = 0; i < COUNT; i++) {EXPECT_EQ(ARRAY1[i],ARRAY2[i]);}

#endif //GAMEGEOMETRY_GLOBALTESTDEFINITIONS_H
